package fr.parcoursup.algos.propositions.donnees;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

import org.apache.logging.log4j.Logger;

import fr.parcoursup.algos.utils.UtilService;

public class StatementMonitoring implements Statement {

	private Statement st;
	
	private Logger logger;
	
	
	public StatementMonitoring(Statement st, Logger logger) {
		super();
		this.st = st;
		this.logger = logger;
	}

	@Override
	public <T> T unwrap(Class<T> iface) throws SQLException {
		return st.unwrap(iface);
	}

	@Override
	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		return st.isWrapperFor(iface);
	}

	@Override
	public ResultSet executeQuery(String sql) throws SQLException {
		logger.info(UtilService.petitEncadrementLog("Execution de la requête : " + sql));
		return st.executeQuery(sql);
	}

	@Override
	public int executeUpdate(String sql) throws SQLException {
		return st.executeUpdate(sql);
	}

	@Override
	public void close() throws SQLException {
		st.close();

	}

	@Override
	public int getMaxFieldSize() throws SQLException {
		return st.getMaxFieldSize();
	}

	@Override
	public void setMaxFieldSize(int max) throws SQLException {
		st.setMaxFieldSize(max);

	}

	@Override
	public int getMaxRows() throws SQLException {
		return st.getMaxRows();
	}

	@Override
	public void setMaxRows(int max) throws SQLException {
		// TODO Auto-generated method stub
		st.setMaxRows(max);
	}

	@Override
	public void setEscapeProcessing(boolean enable) throws SQLException {
		// TODO Auto-generated method stub
		st.setEscapeProcessing(enable);
	}

	@Override
	public int getQueryTimeout() throws SQLException {
		// TODO Auto-generated method stub
		return st.getQueryTimeout();
	}

	@Override
	public void setQueryTimeout(int seconds) throws SQLException {
		// TODO Auto-generated method stub
		st.setQueryTimeout(seconds);
	}

	@Override
	public void cancel() throws SQLException {
		// TODO Auto-generated method stub
		st.cancel();
	}

	@Override
	public SQLWarning getWarnings() throws SQLException {
		// TODO Auto-generated method stub
		return st.getWarnings();
	}

	@Override
	public void clearWarnings() throws SQLException {
		// TODO Auto-generated method stub
		st.clearWarnings();
	}

	@Override
	public void setCursorName(String name) throws SQLException {
		// TODO Auto-generated method stub
		st.setCursorName(name);
	}

	@Override
	public boolean execute(String sql) throws SQLException {
		// TODO Auto-generated method stub
		return st.execute(sql);
	}

	@Override
	public ResultSet getResultSet() throws SQLException {
		// TODO Auto-generated method stub
		return st.getResultSet();
	}

	@Override
	public int getUpdateCount() throws SQLException {
		// TODO Auto-generated method stub
		return st.getUpdateCount();
	}

	@Override
	public boolean getMoreResults() throws SQLException {
		// TODO Auto-generated method stub
		return st.getMoreResults();
	}

	@Override
	public void setFetchDirection(int direction) throws SQLException {
		// TODO Auto-generated method stub
		st.setFetchDirection(direction);
	}

	@Override
	public int getFetchDirection() throws SQLException {
		// TODO Auto-generated method stub
		return st.getFetchDirection();
	}

	@Override
	public void setFetchSize(int rows) throws SQLException {
		st.setFetchSize(rows);
	}

	@Override
	public int getFetchSize() throws SQLException {
		return st.getFetchSize();
	}

	@Override
	public int getResultSetConcurrency() throws SQLException {
		return st.getResultSetConcurrency();
	}

	@Override
	public int getResultSetType() throws SQLException {
		return st.getResultSetType();
	}

	@Override
	public void addBatch(String sql) throws SQLException {
		st.addBatch(sql);
	}

	@Override
	public void clearBatch() throws SQLException {
		st.clearBatch();
	}

	@Override
	public int[] executeBatch() throws SQLException {
		return st.executeBatch();
	}

	@Override
	public Connection getConnection() throws SQLException {
		return st.getConnection();
	}

	@Override
	public boolean getMoreResults(int current) throws SQLException {
		return st.getMoreResults();
	}

	@Override
	public ResultSet getGeneratedKeys() throws SQLException {
		return st.getGeneratedKeys();
	}

	@Override
	public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
		return st.executeUpdate(sql, autoGeneratedKeys);
	}

	@Override
	public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
		return st.executeUpdate(sql, columnIndexes);
	}

	@Override
	public int executeUpdate(String sql, String[] columnNames) throws SQLException {
		return st.executeUpdate(sql, columnNames);
	}

	@Override
	public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
		return st.execute(sql, autoGeneratedKeys);
	}

	@Override
	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		return st.execute(sql, columnIndexes);
	}

	@Override
	public boolean execute(String sql, String[] columnNames) throws SQLException {
		return st.execute(sql, columnNames);
	}

	@Override
	public int getResultSetHoldability() throws SQLException {
		return st.getResultSetHoldability();
	}

	@Override
	public boolean isClosed() throws SQLException {
		return st.isClosed();
	}

	@Override
	public void setPoolable(boolean poolable) throws SQLException {
		st.setPoolable(poolable);
	}

	@Override
	public boolean isPoolable() throws SQLException {
		return st.isPoolable();
	}

	@Override
	public void closeOnCompletion() throws SQLException {
		st.closeOnCompletion();
	}

	@Override
	public boolean isCloseOnCompletion() throws SQLException {
		return st.isCloseOnCompletion();
	}

}
